### ISSUE TITLE
ImportError: /home/mona/Downloads/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/OpenEXR.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN13IlmThread_3_14TaskE

### ISSUE THREAD

**Issue by monajalal** [AcademySoftwareFoundation/openexr#1618]
Could you please help me with this error? I am using the bundled Python 3.10 inside Blender 3.5:

```
(base) mona@ada:~/pvnet-rendering$ /home/mona/Downloads/blender-3.5.1-linux-x64/3.5/python/bin/python3.10 run.py --type rendering
Traceback (most recent call last):
  File "/home/mona/pvnet-rendering/run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "/home/mona/pvnet-rendering/run.py", line 11, in run_rendering
    from blender.render_utils import Renderer, YCBRenderer
  File "/home/mona/pvnet-rendering/blender/render_utils.py", line 9, in <module>
    import OpenEXR
ModuleNotFoundError: No module named 'OpenEXR'
(base) mona@ada:~/pvnet-rendering$ /home/mona/Downloads/blender-3.5.1-linux-x64/3.5/python/bin/pip  install openexr
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting openexr
  Downloading OpenEXR-1.3.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (534 bytes)
Downloading OpenEXR-1.3.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.7 MB/s eta 0:00:00
DEPRECATION: pytorch-lightning 1.6.0 has a non-standard dependency specifier torch>=1.8.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: openexr
Successfully installed openexr-1.3.9
(base) mona@ada:~/pvnet-rendering$ /home/mona/Downloads/blender-3.5.1-linux-x64/3.5/python/bin/python3.10 run.py --type rendering
Traceback (most recent call last):
  File "/home/mona/pvnet-rendering/run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "/home/mona/pvnet-rendering/run.py", line 11, in run_rendering
    from blender.render_utils import Renderer, YCBRenderer
  File "/home/mona/pvnet-rendering/blender/render_utils.py", line 9, in <module>
    import OpenEXR
ImportError: /home/mona/Downloads/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/OpenEXR.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN13IlmThread_3_14TaskE

```

**Comment by cary-ilm** [comment]
Culling old issues.  I believe this has been resolved with the newer releases of the python module, but if it's still a problem, feel free to reopen or file a new issue.
